kind: Service
apiVersion: v1
metadata:
  name:  expo-ui-service
spec:
  selector:
    app:  expo-ui
  type:  NodePort
  ports:
  - name:  http
    port:  80
    targetPort:  80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  expo-ui
  labels:
    name:  expo-ui
    app: expo-ui
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  expo-ui
    spec:
      restartPolicy: Always
      containers:
      - imagePullPolicy: Always
        image:  ipedrazas/docmock
        name:  expo-ui
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        # livenessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 5000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 10
        # env:
        # - name:  ENVVARNAME
        #   value:  ENVVARVALUE       
        ports:
        - containerPort:  80
          name:  expo-ui-port
        # volumeMounts:
        # - mountPath: /data
        #   name: data
      # volumes:
      #   - name: data
      #     emptyDir: {}
      